---
title: "ATLANTIC AMPHIBIANS: a data set of amphibian communities from the Atlantic Forests of South America"
description: |
  Here we present a data set containing information about amphibian communities sampled throughout the Atlantic Forest Biome in South America. The data were extracted from 389 bibliographic references (articles, books, theses, and dissertations) representing inventories of amphibian communities from 1940 to 2017.
categories:
  - Papers 
#  - 2018
date: 06-28-2018
preview: amphibians.png
output:
  distill::distill_article:
    self_contained: false

---
**Authors:** *Maurício Humberto Vancine, Kauã da Silva Duarte, **Yuri Silva de Souza**, João Gabriel Ribeiro Giovanelli, Paulo Mateus Martins-Sobrinho, Ariel López, Rafael Parelli Bovo, Fábio Maffei, Marília Bruzzi Lion, José Wagner Ribeiro Júnior, Ricardo Brassaloti, Carolina Ortiz Rocha da Costa, Henrique Oliveira Sawakuchi, Lucas Rodriguez Forti, Pier Cacciali, Jaime Bertoluci, Célio Fernando Baptista Haddad, Milton Cezar Ribeiro*


## **Abstract**

Amphibians are among the most threatened vertebrates in the world and this is also true for those inhabiting the Atlantic Forest hotspot, living in ecosystems that are highly degraded and threatened by anthropogenic activities. We present a data set containing information about amphibian communities sampled throughout the Atlantic Forest Biome in South America. The data were extracted from 389 bibliographic references (articles, books, theses, and dissertations) representing inventories of amphibian communities from 1940 to 2017. The data set includes 17,619 records of 528 species with taxonomic certainty, from 1,163 study sites. Of all the records, 14,450 (82%) were classified using the criterion of endemism; of those, 7,787 (44%) were considered endemic and 6,663 (38%) were not. Historically, multiple sampling methods were used to survey amphibians, the most representative methods being active surveys (82.1%), surveys at breeding sites (20%), pitfall traps (15.3%), and occasional encounters (14.5%). Species richness averaged 15.2 ± 11.3 (mean ± SD), ranging from 1 to 80 species per site. We found a low dominance in the communities, with 10 species occurring in about 26% of communities: Physalaemus cuvieri (4.1%), Dendropsophus minutus (3.8%), Boana faber (3.1%), Scinax fuscovarius (2.8%), Leptodactylus latrans (2.7%), Leptodactylus fuscus (2.6%), Boana albopunctata (2.3%), Dendropsophus nanus (1.6%), Rhinella ornata (1.6%), and Leptodactylus mystacinus (1.6%). This data set represents a major effort to compile inventories of amphibian communities for the Neotropical region, filling a large gap in the data on the Atlantic Forest hotspot. We hope this data set can be used as a credible tool in the proposal of new studies on amphibian sampling and even in the development of conservation planning for these taxa. This information also has great relevance for macroecological studies, being foundational for both conservation and restoration strategies in this biodiversity hotspot. No copyright or proprietary restrictions are associated with the use of this data set. Please cite this data paper when the data are used in publications or teaching events.

Click on the link below for further information about this paper: [https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.2392](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.2392)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->