---
title: "Building my 1st ShinyApp"
description: |
  This was my first experience building a ShinyApp. I created this app to host the dataset I used during my master's.
categories:
  - ShinyApp
  - databases 
author:
  - name: Yuri Souza
date: 2022-09-24
preview: defau.gif
output:
  distill::distill_article:
    self_contained: false

---
During my master's, I had the idea to make the data I used public and easily accessible to everyone. So, I found the [ShinyApp](https://shiny.rstudio.com/) structure. Since I was already working and familiar with the R language, I thought it would be good to use its package to share my data. 

The idea was to create an interactive app with a website layout in which the user could see the details of the project as exploring the data information. 

The project tries to understand the impact of the vertebrates' Defaunation in the Brazilian Atlantic forest. That is why we called it [**DEFAU-Biota**](https://souzayuri.shinyapps.io/biota/). Here the user can scroll through the app and check the information about the sampled areas, camera trap videos, fieldwork, and scientific publications, and interact with the data using a linear model.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<iframe src="https://souzayuri.shinyapps.io/biota/"
        style="border: 2px solid black; width: 120%; height: 500px;"></iframe>
        

<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->