---
title: "Murundus: hotspots of biodiversity, nutrient enrichment, and gas fluxes through termite activity"
description: |
  This poster was presented on the University of Miami Graduate Student Symposium 2023
categories:
  - Poster Presentation
#  - 2022
date: 01-06-2023
preview: conceptual_model9.png
output:
  distill::distill_article:
    self_contained: true

---
**Authors:** *Yuri Souza & Amy Zanne*

This poster is a draft of what I want to approach and investigate during my Ph.D. I made this presentation for the University of Miami Graduate Student Symposium 2023, which awarded me for presenting the best poster at this symposium. 

# **Abstract**
## **Abstract**
### **Abstract**

Campos de Murundus, or earthmounds, are discrete mounds surrounded by grass common throughout the Brazilian Savanna. Such sites favor colonization by plants and by termites, which play a significant role in ecosystem dynamics and maintenance through organic matter decomposition and gas fluxes. I aim to address how Campos de Murundus drives ecosystem dynamics in a spatial gradient. For this, we will perform a literature review to understand the role of such islands worldwide, and we will conduct fieldwork and data collection in the Brazilian Savanna Cerrado, focusing on the Campos de Murundus islands. We hypothesize the existence of a gradient of termite diversity, soil nutrient enrichment, plant functional composition, and gas fluxes increasing from an open grass field of the Savanna to the Murundus.


Unfortunately, our poster size is too large, so it was impossible to load with a high resolution on this post. Please click [here](https://github.com/souzayuri/betterposter_um_grad_symp_2023/blob/main/Yuri_Souza_PSI_poster.pdf) to access it from my GitHub and check the details of our research.

<embed src="Yuri_Souza_PSI_poster_resized.pdf" type="application/pdf" width="100%" height="600px" />

<!--<embed src="Yuri_Souza_PSI_poster_resized.pdf#toolbar=0&navpanes=0&scrollbar=0" type="application/pdf" width="100%" height="600px" />

<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->

<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
