---
title: "Frugivory and seed dispersal by the Red-footed Tortoise Chelonoidis carbonaria"
description: |
  Here, we assessed the maximum width of seeds this species could ingest, the mean gut retention time (GRT), and the post-consumption germination capacity for tropical fruit species.
categories:
  - Papers 
#  - 2022
date: 10-21-2022
preview: tortoise_frugivory.png
output:
  distill::distill_article:
    self_contained: true

---
**authors:** *Lais Lautenschlager, Yuri Souza, Mauro Galetti*


## **Abstract**

Seed dispersal by frugivores is essential in plant life cycles, with birds and mammals the principal and well-studied dispersal agents. However, there is an increasing recognition that terrestrial tortoises could also be considered important seed dispersers in many ecosystems. The red-footed tortoise (*Chelonoidis carbonaria*) is one of the largest terrestrial tortoises in South America and is thought to disperse large seeds. However, little is known about their role as seed dispersers, and their potential use as restorers of defaunated areas. Here, we assessed the maximum width of seeds this species could ingest, the mean gut retention time (GRT), and the post-consumption germination capacity for tropical fruit species. Forty different fruit species were offered to eight captive individuals, obtaining a maximum seed width swallowed of 23 mm. We used four native plant species to measure the GRT within four tortoises, and we found a mean retention time of 18.92 ± 4.81 days. We also found that sex is an important indicator of GRT, with females presenting longer retention periods. This novel finding may be due to the higher metabolic defecating and dispersing rates of males. Although germination proportions varied between the four plant species used in the experiment, overall defecated seeds germinated faster than control seeds. We conclude that red-footed tortoises are potentially important seed dispersers due to their ability to swallow a large quantity and size of seeds while accelerating seed germination rates. This species should be considered a viable ecological substitute for large frugivores in rewilding projects, as *C. carbonaria* performs similar functions to large dispersers that have been extirpated due to defaunation processes.

Click on the link below for further information about this paper: [https://doi.org/10.1016/j.actao.2022.103837](https://doi.org/10.1016/j.actao.2022.103837)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
