---
title: "ATLANTIC MAMMALS: a data set of assemblages of medium-and large-sized mammals of the Atlantic Forest of South America"
description: |
  Here, we present the ATLANTIC MAMMALS, an open data set on information on medium- and large-sized mammal assemblages in the Atlantic Forest of Brazil, Paraguay, and Argentina. A total of 129 studies were compiled, including published and in press peer-reviewed papers, book chapters, theses and unpublished data.
categories:
  - Papers 
#  - 2019
date: 06-10-2019
preview: data_paper_mamals.png
output:
  distill::distill_article:
    self_contained: false

---
**Authors:** ***Yuri Souza**, Fernando Gonçalves, Laís Lautenschlager, Paula Akkawi,Calebe Mendes, Mariana M. Carvalho, Ricardo S. Bovendorp, Hugo Fernandes-Ferreira, Clarissa Rosa,Maurício Eduardo Graipel, Nivaldo Peroni, Jorge José Cherem, Juliano André Bogoni, Carlos Rodrigo Brocardo, João Miranda, Luciana Zago da Silva, Geruza Melo, Nilton Cáceres, Jonas Sponchiado, Milton Cezar Ribeiro, Mauro Galetti*


## **Abstract**

Biodiversity inventories contain important information about species richness, community structure, and composition, and are the first step in developing any conservation and mitigation strategies. The Atlantic Forest of South America is home to around 334 species of small-, medium-, and large-sized mammals, and is currently restricted to less than 12% of its original cover. Here, we present the ATLANTIC MAMMALS, an open data set on information on medium- and large-sized mammal assemblages in the Atlantic Forest of Brazil, Paraguay, and Argentina. A total of 129 studies were compiled, including published and in press peer-reviewed papers, book chapters, theses and unpublished data. We mapped 244 assemblages, eight orders, 63 genera, and 94 species (24 of which are classified as threatened by the IUCN Red List) distributed in 128 protected and 116 unprotected areas. Species richness of the mammalian assemblages varied from 1 to 39 species (mean 15). The most recorded species in the entire biome was Dasypus novemcinctus, followed by Cerdocyon thous and Procyon cancrivorous. These data can be useful in support of macroecological studies and conservation planning strategies. Please cite this data paper when the data are used in publications. We also request that researchers and teachers inform us of how they are using the data.

Click on the link below for further information about this paper: [https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.2785](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.2785)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->