on:
  repository_dispatch:
  push:
    branches: master

name: Render & Deploy Site

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies, save github token for gh(), render site
        run: |
          github_token <- "${{ secrets.GITHUB_TOKEN }}"
          install.packages(c("distill", "postcards", "devtools", "httr",
          "fs", "htmltools", "here", "magick", "gh", "jsonlite", "echarts4r.assets"))
          rmarkdown::render_site(encoding = "UTF-8")
        shell: Rscript {0}
        
      - name: Copy gallery images
        run: Rscript -e 'fs::dir_copy("gallery/img", "docs/gallery/img")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
